### ISSUE TITLE
Erro ao fazer build docker

### ISSUE THREAD

**Issue by monstrodopantano** [cogumm/NextLevelWeek#18]
Olá Gabriel,

Estava estudando algumas coisas sobre node, react... E me deparei com seu projeto dai segui o seu "Who to use" e me retornou o seguinte erro:

`$ ts-node-dev ./node_modules/typeorm/cli.js migration:run
[INFO] 13:00:37 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
Error during migration run:

TypeError: someClass is not a constructor
    at class_1.get (/app/nwl04_api/src/container.ts:34:51)
    at Object.getFromContainer (/app/nwl04_api/src/container.ts:71:29)
    at /app/nwl04_api/src/connection/ConnectionMetadataBuilder.ts:35:58
    at Array.map (<anonymous>)
    at ConnectionMetadataBuilder.buildMigrations (/app/nwl04_api/src/connection/ConnectionMetadataBuilder.ts:35:36)
    at Connection.buildMetadatas (/app/nwl04_api/src/connection/Connection.ts:521:54)
    at Connection.<anonymous> (/app/nwl04_api/src/connection/Connection.ts:193:18)
    at step (/app/nwl04_api/node_modules/tslib/tslib.js:143:27)
    at Object.next (/app/nwl04_api/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/app/nwl04_api/node_modules/tslib/tslib.js:114:62)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'api' failed to build: The command '/bin/sh -c yarn typeorm migration:run' returned a non-zero code: 1`

**Comment by monstrodopantano** [comment]
Desculpa o erro foi devido a falta da configuração do .env, ou seja está tudo certo com o projeto.
Grande abraço

**Comment by cogumm** [comment]
Boa tarde @monstrodopantano desculpa estava sem PC por alguns dias.

Que bom que deu certo.

Abraços.
